
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/bmizerany/assert"

[[constraint]]
  name = "github.com/natefinch/pie"

[[constraint]]
  name = "github.com/sirupsen/logrus"

[[constraint]]
  name = "github.com/xyproto/kinnian"

[[constraint]]
  name = "github.com/xyproto/permissionbolt"

[[constraint]]
  name = "github.com/xyproto/permissions2"

[[constraint]]
  name = "github.com/xyproto/pinterface"

[[constraint]]
  name = "github.com/xyproto/simplebolt"

[[constraint]]
  name = "github.com/xyproto/simpleredis"
